# Generated by Django 5.2.6 on 2025-09-16 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('bola sepak', 'Bola Sepak'), ('bola latihan', 'Bola Latihan'), ('pakaian', 'Pakaian'), ('sepatu sepak bola', 'Sepatu Sepak Bola'), ('aksesoris', 'Aksesoris'), ('gawang', 'Gawang'), ('budget', 'Budget')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
