# Generated by Django 5.2.6 on 2025-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
