# Generated by Django 5.2.6 on 2025-09-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bola sepak', 'Bola Sepak'), ('bola latihan', 'Bola Latihan'), ('pakaian', 'Pakaian'), ('sepatu sepak bola', 'Sepatu Sepak Bola'), ('aksesoris', 'Aksesoris'), ('gawang', 'Gawang'), ('budget', 'Budget')], default='update', max_length=20),
        ),
    ]
