# Generated by Django 5.2.5 on 2025-09-15 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('bola sepak', 'Bola Sepak'), ('bola latihan', 'Bola Latihan'), ('pakaian', 'Pakaian'), ('sepatu sepak bola', 'Sepatu Sepak Bola'), ('aksesoris', 'Aksesoris'), ('gawang', 'Gawang'), ('budget', 'Budget')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
